#get the directory of this makefile
LIB:=$(CLAW)/geoclaw_1d/src/1d_nonuniform

#list of common sources:
COMMON_MODULES += \
  $(LIB)/utility_module.f90 \
  $(LIB)/geoclaw_module.f90 \
  $(LIB)/gauges_module.f90 \
  $(LIB)/grid_module.f90 \

COMMON_SOURCES += \
  $(LIB)/claw1.f \
  $(LIB)/rp1_geoclaw.f90 \
  $(LIB)/bc1.f \
  $(LIB)/setaux.f \
  $(LIB)/out1.f \
  $(LIB)/setprob.f90 \
  $(LIB)/b4step1.f90 \
  $(LIB)/src1.f90 \
  $(CLAW)/classic/src/1d/driver.f90 \
  $(CLAW)/classic/src/1d/qinit.f \
  $(CLAW)/classic/src/1d/claw1ez.f \
  $(CLAW)/classic/src/1d/inlinelimiter.f90 \
  $(CLAW)/classic/src/1d/step1.f90 \
  $(CLAW)/classic/src/1d/copyq1.f \
  $(CLAW)/classic/src/1d/opendatafile.f \
  $(CLAW)/riemann/src/geoclaw_riemann_utils.f \
